# Generated by Django 6.0.3 on 2026-05-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={},
        ),
    ]
