# Generated by Django 6.0.3 on 2026-05-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={},
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS emergency_contacts (
                id UUID PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES "USERS"(id) DEFERRABLE INITIALLY DEFERRED,
                contact_name VARCHAR(255) NOT NULL,
                relationship VARCHAR(255) NOT NULL,
                phone_number VARCHAR(255) NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS emergency_contacts;"
        ),
    ]
