# Generated by Django 6.0.3 on 2026-05-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soseventlog',
            table='service_call_logs',
        ),
    ]
